### ISSUE TITLE
license 파일 생성

### ISSUE THREAD

**Issue by YJY1220** [devrel-kr/azure-metric-advisor-quickstart#7]
**Content**
오픈소스 azure-sdk에서 생성한 repository의 azure-metric-advisor-quickstart에서 commit한 코드는 다른 곳의 코드를 참고한 것이다. 이렇게 참고한 코드처럼 저작권 보유자 이외의 다른 사람에게 코드를 사용할 권한을 부여하는 유일한 방법이기 때문에 라이선스를 고지하고 전체 라이선스 텍스트를 제공했다. 
그래서 azure-sdk를 올리신 분들의 license를 보고 이 소프트웨어를 누구라도 무상으로 제한없이 취급해도 좋고 저자 또는 저작권자는 소프트웨어에 아무런 책임을 지지 않는다는 MIT license로 등록했다.  

**Caution**
지금은 다른 분들도 azure-sdk시에 라이센스 파일을 MIT license로 했기 때문에 MIT license로 commit했지만 만약 다른 분들이 이 license가 아닌 다른 특별한 license로 했을 경우 이를 고려해야한다.

**Comment by YJY1220** [comment]
b5e9dd94415c4c7dbfd238c265406980282395ae 으로 commit 했습니다.

**Comment by Gyeonghun-Park** [comment]
해당 이슈는 해결이 되어 클로즈 하겠습니다. 수고하셨습니다!
